version: '2'
services:
    db:
      image: gcavalcante8808/zabbix-db-postgres
      environment:
        POSTGRES_DB: zabbix
        POSTGRES_USER: zabbix
        POSTGRES_PASSWORD: "zabbix"
      volumes:
        - ./pgdata:/var/lib/postgresql/data

    server:
      image: gcavalcante8808/zabbix-server
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: zabbix
        DB_PASS: zabbix
        DB_NAME: zabbix
        DB_TYPE: POSTGRESQL
      volumes:
       - ./zabbix-server-conf:/usr/local/etc/zabbix_server.conf.d
       - ./zabbix-server-scripts:/usr/local/share/zabbix/externalscripts
      ports:
       - "10051:10051"
      depends_on:
       - db

    frontend:
      image: gcavalcante8808/zabbix-frontend
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: zabbix
        DB_PASS: zabbix
        DB_NAME: zabbix
        DB_TYPE: POSTGRESQL
        ZBX_SERVER: server
        ZBX_SERVER_PORT: 10051
        ZBX_SERVER_NAME: "Zabbix Docker"
      ports:
        - "80:80"
      depends_on:
       - db
       - server
